name: restart_app
description: A simple package that helps you to restart the whole android app with a single function call.
version: 1.1.0
homepage: https://github.com/gabrimatic/restart

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: gabrimatic.info.restart
        pluginClass: RestartPlugin
      ios:
        pluginClass: RestartAppPlugin
      web:
        pluginClass: RestartWeb
        fileName: restart_web.dart